import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Search as SearchIcon } from "lucide-react";
import { cn } from "@/lib/utils";

import { Button } from "@/components/ui/button";
import { SearchLauncher } from "@/components/SearchLauncher";
import { ThemeProvider } from "@/components/theme-provider";
import { Icons } from "@/components/icons";

import "./globals.css";
import { Inter } from "next/font/google";
import { Oswald } from "next/font/google";
import { Amatic_SC } from "next/font/google";

import { NavigationMenuDemo } from "@/components/Nav";

import { LayoutProvider } from "@/hooks/use-layout";

import { SiteHeader } from "@/components/site-header";

import { ActiveThemeProvider } from "@/components/active-theme";

import { META_THEME_COLORS, siteConfig } from "@/lib/config";

import Logo from "@/components/Logo";

const footerNav = [
  {
    title: "Навигация",
    links: [
      { label: "Главная", href: "/" },
      { label: "Статьи", href: "/articles" },
      { label: "Обо мне", href: "/docs" },
    ],
  },
  {
    title: "Проекты",
    links: [
      {
        label: "mem.frontend",
        href: "https://github.com/mezhinsky/MosEisleyModels/tree/main/mem.frontend",
        external: true,
      },
      {
        label: "mem.backend",
        href: "https://github.com/mezhinsky/MosEisleyModels/tree/main/mem.backend",
        external: true,
      },
      {
        label: "mem.admin",
        href: "https://github.com/mezhinsky/MosEisleyModels/tree/main/mem.admin",
        external: true,
      },
    ],
  },
  {
    title: "Контакты",
    links: [
      { label: "Telegram", href: "https://t.me/mezhinsky", external: true },
      { label: "Email", href: "mailto:hello@mezhinsky.dev" },
      { label: "Github", href: "https://github.com/mezhinsky", external: true },
    ],
  },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
  display: "swap",
});

const oswald = Oswald({
  subsets: ["latin", "cyrillic"],
  variable: "--font-oswald",
  display: "swap",
});

export const amatic = Amatic_SC({
  subsets: ["latin", "cyrillic"],
  variable: "--font-amatic",
  weight: ["400", "700"], // у Amatic SC только два веса
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.theme === 'dark' || ((!('theme' in localStorage) || localStorage.theme === 'system') && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.querySelector('meta[name="theme-color"]').setAttribute('content', '${META_THEME_COLORS.dark}')
                }
                if (localStorage.layout) {
                  document.documentElement.classList.add('layout-' + localStorage.layout)
                }
              } catch (_) {}
            `,
          }}
        />
        <meta name="theme-color" content={META_THEME_COLORS.light} />
      </head>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          inter.variable,
          oswald.variable,
          amatic.variable,
          "antialiased min-h-screen bg-gray-50 dark:bg-gray-900",
          "group/body overscroll-none",
          "[--footer-height:calc(var(--spacing)*14)]",
          "[--header-height:calc(var(--spacing)*14)]",
          "xl:[--footer-height:calc(var(--spacing)*24)]"
        )}
      >
        <ThemeProvider>
          <LayoutProvider>
            <ActiveThemeProvider>
              <div
                data-slot="layout"
                className="bg-background relative z-10 flex min-h-svh flex-col"
              >
                <SiteHeader />
                <main className="container-wrapper 3xl:fixed:px-0 px-6">
                  {children}
                </main>
              </div>
              <footer className="py-8 px-4 border-t border-gray-200 dark:border-gray-800 bg-white/60 dark:bg-gray-900/60 backdrop-blur">
                <div className="container-wrapper 3xl:fixed:px-0 px-6 mx-auto grid gap-8 md:grid-cols-[1.2fr_1fr_1fr_1fr] items-start">
                  <div className="space-y-3">
                    <Button
                      asChild
                      variant="ghost"
                      size="icon"
                      className="size-11 lg:flex fill-indigo-700"
                    >
                      <Link href="/">
                        <Icons.logo className="size-8" />
                        <span className="sr-only">{siteConfig.name}</span>
                      </Link>
                    </Button>
                    <p className="text-sm text-gray-600 dark:text-gray-400">
                      Наблюдения, практики и эксперименты из разработки и
                      продакшена.
                    </p>
                    <p className="text-xs text-gray-500 dark:text-gray-500">
                      © {new Date().getFullYear()} mezhinsky
                    </p>
                  </div>

                  {footerNav.map((section) => (
                    <div key={section.title} className="space-y-3">
                      <div className="text-sm font-semibold text-gray-900 dark:text-gray-100">
                        {section.title}
                      </div>
                      <ul className="space-y-2">
                        {section.links.map((link) => (
                          <li key={`${section.title}-${link.label}`}>
                            <Link
                              href={link.href}
                              target={link.external ? "_blank" : undefined}
                              rel={link.external ? "noreferrer" : undefined}
                              className="text-sm text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100 transition-colors"
                            >
                              {link.label}
                            </Link>
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </footer>
            </ActiveThemeProvider>
          </LayoutProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
