import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Search as SearchIcon } from "lucide-react";

import { Button } from "@/components/ui/button";
import { SearchLauncher } from "@/components/SearchLauncher";

import "./globals.css";
import { Inter } from "next/font/google";
import { Oswald } from "next/font/google";
import { Amatic_SC } from "next/font/google";

import { NavigationMenuDemo } from "@/components/Nav";

import { SiteHeader } from "@/components/site-header";

import Logo from "@/components/Logo";

const footerNav = [
  {
    title: "Навигация",
    links: [
      { label: "Главная", href: "/" },
      { label: "Статьи", href: "/articles" },
      { label: "Обо мне", href: "/docs" },
    ],
  },
  {
    title: "Проекты",
    links: [
      {
        label: "mem.frontend",
        href: "https://github.com/mezhinsky/MosEisleyModels/tree/main/mem.frontend",
        external: true,
      },
      {
        label: "mem.backend",
        href: "https://github.com/mezhinsky/MosEisleyModels/tree/main/mem.backend",
        external: true,
      },
      {
        label: "mem.admin",
        href: "https://github.com/mezhinsky/MosEisleyModels/tree/main/mem.admin",
        external: true,
      },
    ],
  },
  {
    title: "Контакты",
    links: [
      { label: "Telegram", href: "https://t.me/mezhinsky", external: true },
      { label: "Email", href: "mailto:hello@mezhinsky.dev" },
      { label: "Github", href: "https://github.com/mezhinsky", external: true },
    ],
  },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
  display: "swap",
});

const oswald = Oswald({
  subsets: ["latin", "cyrillic"],
  variable: "--font-oswald",
  display: "swap",
});

export const amatic = Amatic_SC({
  subsets: ["latin", "cyrillic"],
  variable: "--font-amatic",
  weight: ["400", "700"], // у Amatic SC только два веса
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` bg-gray-50 dark:bg-gray-900`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${oswald.variable} ${amatic.variable} antialiased min-h-screen bg-gray-50 dark:bg-gray-900`}
      >
        {/* <header className="px-4 border-b border-gray-200 bg-white/70 dark:bg-gray-900/60 backdrop-blur dark:border-gray-800">
          <div className="max-w-5xl mx-auto flex items-center gap-4 py-2">
            <Logo />
            <NavigationMenuDemo />
            <div className="ml-auto">
              <SearchLauncher />
            </div>
          </div>
        </header> */}
        <SiteHeader />
        <main className="min-h-screen py-4 px-4">
          <div className="max-w-5xl mx-auto">{children}</div>
        </main>
        <footer className="py-8 px-4 border-t border-gray-200 dark:border-gray-800 bg-white/60 dark:bg-gray-900/60 backdrop-blur">
          <div className="max-w-5xl mx-auto grid gap-8 md:grid-cols-[1.2fr_1fr_1fr_1fr] items-start">
            <div className="space-y-3">
              <Logo />
              <p className="text-sm text-gray-600 dark:text-gray-400">
                Наблюдения, практики и эксперименты из разработки и продакшена.
              </p>
              <p className="text-xs text-gray-500 dark:text-gray-500">
                © {new Date().getFullYear()} mezhinsky
              </p>
            </div>

            {footerNav.map((section) => (
              <div key={section.title} className="space-y-3">
                <div className="text-sm font-semibold text-gray-900 dark:text-gray-100">
                  {section.title}
                </div>
                <ul className="space-y-2">
                  {section.links.map((link) => (
                    <li key={`${section.title}-${link.label}`}>
                      <Link
                        href={link.href}
                        target={link.external ? "_blank" : undefined}
                        rel={link.external ? "noreferrer" : undefined}
                        className="text-sm text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100 transition-colors"
                      >
                        {link.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </footer>
      </body>
    </html>
  );
}
