import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Search as SearchIcon } from "lucide-react";
import { cn } from "@/lib/utils";

import { Button } from "@/components/ui/button";
import { SearchLauncher } from "@/components/SearchLauncher";
import { ThemeProvider } from "@/components/theme-provider";
import { Icons } from "@/components/icons";

import "./globals.css";
import { Inter } from "next/font/google";
import { Oswald } from "next/font/google";
import { Amatic_SC } from "next/font/google";

import { NavigationMenuDemo } from "@/components/Nav";

import { LayoutProvider } from "@/hooks/use-layout";

import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

import { ActiveThemeProvider } from "@/components/active-theme";

import { META_THEME_COLORS, siteConfig } from "@/lib/config";

import Logo from "@/components/Logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
  display: "swap",
});

const oswald = Oswald({
  subsets: ["latin", "cyrillic"],
  variable: "--font-oswald",
  display: "swap",
});

export const amatic = Amatic_SC({
  subsets: ["latin", "cyrillic"],
  variable: "--font-amatic",
  weight: ["400", "700"], // у Amatic SC только два веса
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.theme === 'dark' || ((!('theme' in localStorage) || localStorage.theme === 'system') && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.querySelector('meta[name="theme-color"]').setAttribute('content', '${META_THEME_COLORS.dark}')
                }
                if (localStorage.layout) {
                  document.documentElement.classList.add('layout-' + localStorage.layout)
                }
              } catch (_) {}
            `,
          }}
        />
        <meta name="theme-color" content={META_THEME_COLORS.light} />
      </head>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          inter.variable,
          oswald.variable,
          amatic.variable,
          "antialiased min-h-screen bg-gray-50 dark:bg-gray-900",
          "group/body overscroll-none",
          "[--footer-height:calc(var(--spacing)*14)]",
          "[--header-height:calc(var(--spacing)*19)]",
          "xl:[--footer-height:calc(var(--spacing)*24)]"
        )}
      >
        <ThemeProvider>
          <LayoutProvider>
            <ActiveThemeProvider>
              <div
                data-slot="layout"
                className="bg-background relative z-10 flex min-h-svh flex-col"
              >
                <SiteHeader />
                <main className="container-wrapper 3xl:fixed:px-0 px-6 py-10">
                  {children}
                </main>
              </div>
              <SiteFooter />
            </ActiveThemeProvider>
          </LayoutProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
